# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_deck.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../nbs/01_deck.ipynb 3
from fastcore.utils import *
from .card import *

# %% ../nbs/01_deck.ipynb 4
class Deck:
  "A deck of 52 cards."
  def __init__(self):
    self.cards = [Card(rank, suit) for suit in range(1, 14) for rank in range(4)]
  def __len__(self):
    return len(self.cards)
  def __contains__(self, card):
    return card in self.cards
  def __str__(self):
    return '; '.join(map(str, self.cards))
  __repr__ = __str__
  

# %% ../nbs/01_deck.ipynb 9
@patch
def pop(self:Deck, 
        idx:int=-1
        ) -> Card:
  "Remove one card from the deck"
  return self.cards.pop(idx)
